### ISSUE TITLE
MaterialUI disables the `Actions` panel

### ISSUE THREAD

**Issue by alejandronanez** [mallowigi/material-theme-ui-lite#105]
**Describe the bug**
I can't get to open the `Actions` panel after setting any Material UI theme as my IDE theme.

**To Reproduce**

I think that I have something misconfigured in my machine as I don't see any other report of this in the repo, so here we go:

1. I pick any of the Material Theme UI Lite themes
2. I open the `Actions` menu
3. Nothing shows up
4. I got this on the error report

```
java.lang.NullPointerException
	at com.mallowigi.idea.themes.MTAbstractThemeAction.getThemeName(MTAbstractThemeAction.kt:53)
	at com.mallowigi.idea.themes.MTAbstractThemeAction.isSelected(MTAbstractThemeAction.kt:45)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.getListCellRendererComponent(GotoActionModel.java:797)
	at com.intellij.ide.actions.searcheverywhere.MixedListFactory$1.getListCellRendererComponent(MixedListFactory.java:81)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:197)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2785)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:443)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:453)
	at java.desktop/javax.swing.DefaultListSelectionModel.addSelectionInterval(DefaultListSelectionModel.java:556)
	at java.desktop/javax.swing.JList.setSelectedIndices(JList.java:2230)
	at com.intellij.ide.actions.searcheverywhere.SEListSelectionTracker.restoreSelection(SEListSelectionTracker.java:74)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$SearchListener.elementsAdded(SearchEverywhereUI.java:1162)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper.lambda$new$0(ThrottlingListenerWrapper.java:38)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper.lambda$new$2(ThrottlingListenerWrapper.java:38)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper$Buffer.flush(ThrottlingListenerWrapper.java:131)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper.searchFinished(ThrottlingListenerWrapper.java:69)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ResultsAccumulator.lambda$searchFinished$6(MixedResultsSearcher.java:334)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ResultsAccumulator.lambda$runInNotificationExecutor$8(MixedResultsSearcher.java:370)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Expected Behavior**
I'd expect that using Material UI Lite, Webstorm keeps working as expected.

**Environment**
```
WebStorm 2022.1.1
Build #WS-221.5591.52, built on May 10, 2022
Licensed to Alejandro Nanez
Subscription is active until March 29, 2023.
Runtime version: 11.0.14.1+1-b2043.45 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.watches.in.variables=false
    documentation.show.toolbar=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.mallowigi.idea (18.0.0)
    atom-one (1.5.1)
    club.nutsoft.Github3Theme (1.1.9)
    com.4lex4.intellij.solarized (2.4.0)
    com.intellij.plugins.vscodekeymap (221.5591.19)
    com.markskelton.one-dark-theme (5.6.0)
    de.netnexus.camelcaseplugin (3.0.12)
    fr.gabrielcolson.prisma.prisma-intellij-plugin (1.2.5)
    mobi.hsz.idea.gitignore (4.4.0)
    ru.adelf.idea.dotenv (2022.1)
    org.rust.lang (0.4.170.4627-221)
    org.toml.lang (221.5591.26)
    quokka.js (1.0.342)
    software.amazon.smithy.intellij (1.4.1)
    wallaby.js (1.0.239)
    com.intellij.lang.jsgraphql (3.1.3)
    mdx.js (1.0.221)
```

**Screenshots**

**Comment by mallowigi** [comment]
Which version are you using ? I remember the version 17 had this issue but 18 shouldn't.

**Comment by alejandronanez** [comment]
👋 @mallowigi is there anything I can do to help debug this issue? Let me know, happy to help!

**Comment by mallowigi** [comment]
I'm kinda busy at the moment, but I've started working on it. In the meantime, please use the toolbar

**Comment by alejandronanez** [comment]
I just updated the plugin to the version released today (June 3rd) and things are working now. Thanks!
