### ISSUE TITLE
Errer every time I start PhpStorm

### ISSUE THREAD

**Issue by b-hayes** [mallowigi/material-theme-ui-lite#109]
**Describe the bug**
I just keep getting an error every time I start the IDE since installing material UI.
Thought Id share:
```
com.intellij.diagnostic.PluginException: ID 'MaterialTheme.ThemeChooser.Dark' is already taken by action 'Dark Themes ()' (class com.intellij.openapi.actionSystem.impl.ChameleonAction)  (Plugin: Material Theme UI Lite). Action 'null (null)' (class com.intellij.openapi.actionSystem.ActionGroupStub) cannot use the same ID com.chrisrm.idea.MaterialThemeUI [Plugin: com.chrisrm.idea.MaterialThemeUI]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionIdCollision(ActionManagerImpl.java:1330)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1264)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerOrReplaceActionInner(ActionManagerImpl.java:718)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processGroupElement(ActionManagerImpl.java:787)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processGroupElement(ActionManagerImpl.java:856)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:488)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerActions(ActionManagerImpl.java:169)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:141)
	at com.jetbrains.rdserver.ui.actionPopupMenu.BackendActionManager.<init>(BackendActionManager.kt:17)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:891)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:29)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame.lambda$prepareToShow$1(WelcomeFrame.java:163)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```
Not sure if this is the right repo might be the full version. I cant remember I jsut wanted to isntall the project frame and it made me install the full plugin as well.

Also this bug might be why I have full version for free without paying (unless you gave it to me for being so nice to you lol).

**To Reproduce**

1. installed project frame and acapt everything it says to installe what it needs.
2. click through the wizard selecting defaults to get to the project frame option and turn it on.
3. then manually change the theme back to the standard darcula wich is difficult after installing meterial themes for some reason.
4. see error.

**Expected Behavior**
No error.

**Environment**
PhpStorm 2022.1.3 (the arm64 version for m1)
Build #PS-221.5921.28, built on June 22, 2022=
Runtime version: 11.0.15+10-b2043.56 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
<img width="673" alt="image" src="https://user-images.githubusercontent.com/30540495/177519718-7991554a-3817-47ff-a082-f18828fc9663.png">

**Comment by mallowigi** [comment]
Looks like the "Dark Themes" plugin author shamelessly copied the Material Themes. Please report to him.

**Comment by b-hayes** [comment]
IM confused. The error directs me to you githubpage and I dont have a plugin called dark themes.

**Comment by mallowigi** [comment]
My bad, I read too fast, because I know of such a plugin and I was thinking that they could have used the same code as in the plugin.

But "dark themes" in this case refers to the Material theme Ui plugin (the main one), meaning that you've been using the lite and main plugin together.

Can you confirm?

**Comment by b-hayes** [comment]
Yeah I guess they are conflicting with each other, this is what I have:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/30540495/177746340-d022f557-16e5-49dd-afb5-d7d60a1f3984.png">

I think what happened was this:

- installed Material UI Lite
- found project frame as a separate plugin and installed that
- project frame asked for material UI to be installed and installed that too

And then the project frame disables itself? 

I was really confused when I installed the project frame and ended up with the full material UI wizard coming up when I just wanted that one feature.

Let me remove everything and start again.

**Comment by mallowigi** [comment]
Just remove the Material UI Lite then.

**Comment by mallowigi** [comment]
Like I explained in the thread - the "Project Frame" plugin is not a standalone plugin, but a "key opener" to some of the premium features. It still needs to be loaded alongside the full plugin, it's not something that can be loaded separately.

**Comment by b-hayes** [comment]
Just in case I removed them all and just installed the project frame again and its all good now.

> Like I explained in the thread - the "Project Frame" plugin is not a standalone plugin, but a "key opener" 

Yeah, I get that but still its confusing.

If I wasn't already familiar with the Material UI wizard Id miss turning the toggle on, and
I imagine that others might wonder why everything about their IDE changed and didn't end up with what they tried to install.

Meh anyways probably not a big deal thanks for sorting me out.
