### ISSUE TITLE
Exception [kotlin.KotlinNullPointerException]

### ISSUE THREAD

**Issue by DITeN-Repo** [mallowigi/material-theme-ui-lite#12]
At first, Thanks for your job!
Rased error on:

**Machine Info:** 
Debian 10.3
JetBrains Rider
**Exception Detail:**
_Note:_ Rased after compile.

`kotlin.KotlinNullPointerException
	at com.intellij.ui.components.BasicOptionButtonUI.getOptionButton(BasicOptionButtonUI.kt:43)
	at com.intellij.ui.components.BasicOptionButtonUI$BaseButton.getBackground(BasicOptionButtonUI.kt:314)
	at java.desktop/javax.swing.JComponent.setBackground(JComponent.java:2751)
	at com.chrisrm.idea.utils.ColorCycle.lambda$new$0(ColorCycle.java:49)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by mallowigi** [comment]
Don't worry, this is not an issue.
