### ISSUE TITLE
Error after open the project

### ISSUE THREAD

**Issue by urameshibr** [mallowigi/material-theme-ui-lite#142]
**Describe the bug**
After open my project appear that error.

**To Reproduce**
1. Open EAP PHPStorm
2. Click on the recent project
3. EAP ask me if i want to use the new design (yes)
4. The project open and show the error

**Expected Behavior**
Just open the project without error

**Environment**
```
PhpStorm 2023.1 EAP
Build #PS-231.7665.36, built on February 27, 2023
Licensed to PhpStorm EAP user: Lucas Rodrigues
Expiration date: March 29, 2023
Runtime version: 17.0.6+10-b829.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 8
Metal Rendering is ON
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    LiveTemplatePreview (0.3)
    me.laria.code.idea_caseconv (0.7.1)
    com.villains.intelij.plugin.newoceantheme (1.2.0)
    com.mallowigi.idea (18.1.0)
    de.netnexus.camelcaseplugin (3.0.12)
    DBN (3.3.6110.0)
    com.intellij.ideolog (203.0.30.0)
    com.yemreak.DarkCode-Theme (1.1)
    dev.pnbarx.idea.treecolor (1.2.2)
    ru.adelf.idea.dotenv (2023.1)
    izhangzhihao.rainbow.brackets (2023.2.6)
    tv.twelvetone.intellij.plugins.intellivue (1.1.28)
    zielu.gittoolbox (500.0.4+213)
```

It should contain:
* OS MacOS Ventura 13.0 ( Macbook Air M1 )
* PhpStorm 2023.1 EAP ( Build #PS-231.7665.36, built on February 27, 2023 )
* Plugin version 18.1.0 -> 20.0.0 (i can update) 

**Screenshots**
```
com.intellij.diagnostic.PluginException: com.intellij.openapi.actionSystem.DefaultActionGroup (MaterialLiteTheme.Menu): group with id "ExperimentalToolbarActions" isn't registered; action will be added to the "Other" group (module=PluginDescriptor(name=Material Theme UI Lite, id=com.mallowigi.idea, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PhpStorm2023.1/plugins/Material Theme UI Lite, version=18.1.0, package=null, isBundled=false))
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:360)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getParentGroup(ActionManagerImpl.java:968)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processAddToGroupNode(ActionManagerImpl.java:917)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processGroupElement(ActionManagerImpl.java:869)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:515)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerActions(ActionManagerImpl.java:168)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:135)
	at com.jetbrains.rdserver.ui.actionPopupMenu.BackendActionManager.<init>(BackendActionManager.kt:15)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:54)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1041)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:19)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:181)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:176)
	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService$suspendImpl(ComponentManagerImpl.kt:1185)
	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService(ComponentManagerImpl.kt)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invokeSuspend(ComponentManagerImpl.kt:1161)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
````

**Comment by mallowigi** [comment]
please update
