### ISSUE TITLE
Theme completely breaks IDEs

### ISSUE THREAD

**Issue by NatsumiHB** [mallowigi/material-theme-ui-lite#24]
Tried on:
- Manjaro
- Windows 10 20H2
- macOS Catalina

After updating the plugin (or installing it fresh on Linux and mac in my case), it completely breaks the IDE.

This mainly means it renders the IDE unresponsive to any kind of input, menu buttons get highlighted but aren't clickable and if you change the theme inside the "Customization" menu you can't even access the settings anymore. Occasionally it will also completely stop the IDE from loading (infinite splash screen).

I also started the IDEs via the command-line and am getting errors about a function returning `null` when that's an illegal return value.

This affects all 2020.3 IDEs I tried (PyCharm Professional, Rider, CLion, Datagrip).

Log output: 
```
2021-01-18 11:22:44,624 [   1550]  ERROR - nsions.impl.ExtensionPointImpl - @NotNull method com/intellij/util/ui/UIUtil.getListSelectionBackground must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/util/ui/UIUtil.getListSelectionBackground must not return null
        at com.intellij.util.ui.UIUtil.$$$reportNull$$$0(UIUtil.java)
        at com.intellij.util.ui.UIUtil.getListSelectionBackground(UIUtil.java:3194)
        at com.intellij.ui.components.JBList.init(JBList.java:192)
        at com.intellij.ui.components.JBList.<init>(JBList.java:50)
        at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen$1.<init>(TabbedWelcomeScreen.java:85)
        at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen.createListWithTabs(TabbedWelcomeScreen.java:85)
        at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen.<init>(TabbedWelcomeScreen.java:41)
        at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.<init>(FlatWelcomeFrame.java:89)
        at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrameProvider.createFrame(FlatWelcomeFrameProvider.java:27)
        at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame.lambda$createWelcomeFrame$3(WelcomeFrame.java:207)
        at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:55)
        at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.java:57)
        at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame.createWelcomeFrame(WelcomeFrame.java:207)
        at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame.prepareToShow(WelcomeFrame.java:168)
        at com.intellij.idea.IdeStarter.showWizardAndWelcomeFrame(IdeStarter.kt:168)
        at com.intellij.idea.IdeStarter.main(IdeStarter.kt:113)
        at com.intellij.idea.ApplicationLoader$startApp$8.run(ApplicationLoader.kt:239)
        at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

This only happens with this plugin after the newest update.

**Comment by NatsumiHB** [comment]
PS: This also affects the cached plugins and the like after reinstalling, meaning unless you fully delete all associated folders of your IDE your install will remain bricked.

**Comment by mallowigi** [comment]
Actually saw this error myself, but thought this was a bug from IntelliJ.

I'll try to fix asap

**Comment by NatsumiHB** [comment]
Awesome! Thanks for the reply.

**Comment by PashoQ** [comment]
Have same issue. Had to manually remove plugin from plugins folder to be able to start IntelliJ.

**Comment by mallowigi** [comment]
I've fixed it, the update should be available in the next days
