### ISSUE TITLE
On opening IntelliJ with this plugin on a remote IDE it throws an error and crashes

### ISSUE THREAD

**Issue by CraftingDragon007** [mallowigi/material-theme-ui-lite#85]
**Describe the bug**
On opening IntelliJ with this plugin on a remote IDE it throws an error and crashes
It does not happen all the time

**To Reproduce**

1. Install JetBrains Gateway on your pc
2. Open It and start a Connection to a Server with Ubuntu Server 20 and with Java JDK 16 installed
3. Install Material Theme UI
4. Restart IDE and You should see this error, or it crashes immediately 

**Expected Behavior**
You can open the remote IDE and no errors are shown

**Environment**
JetBrains Client 2021.3
Build #JBC-213.5744.223, built on November 27, 2021
Subscription is active until February 26, 2022.
For educational use only.
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
Controller in Remote Development
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    ide.balloon.shadow.size=0
    rdclient.backend.actionHandlers=false

Non-Bundled Plugins:
    org.jraf.intellijplugin.nyantray (1.2.0)
    com.chrisrm.idea.MaterialThemeUI (6.10.1)

**Screenshots**
![image](https://user-images.githubusercontent.com/68032198/145683715-c633be83-a478-4467-a325-ef52665e72fb.png)

**Stacktrace**
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/intellij/history/integration/ui/views/RevisionsList$MyCellRenderer
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/intellij/history/integration/ui/views/RevisionsList$MyCellRenderer
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:450)
	at com.mallowigi.idea.MTLafComponent.initComponent(MTLafComponent.java:122)
	at com.mallowigi.idea.MTLafComponent.appFrameCreated(MTLafComponent.java:73)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:624)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy31.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded(IdeStarter.kt:101)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:80)
	at com.jetbrains.thinclient.ThinClientStarter.main(ThinClientStarter.kt:58)
	at com.intellij.idea.ApplicationLoader$startApp$3.run(ApplicationLoader.kt:190)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	... 8 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/history/integration/ui/views/RevisionsList$MyCellRenderer
	at com.mallowigi.idea.UIReplacer.patchLocalHistory(UIReplacer.java:178)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.java:94)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.java:392)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.java:334)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.java:354)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.java:100)
	at com.mallowigi.idea.MTLafComponent.lambda$initComponent$0(MTLafComponent.java:122)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:450)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.intellij.history.integration.ui.views.RevisionsList$MyCellRenderer PluginClassLoader(plugin=PluginDescriptor(name=Material Theme UI, id=com.chrisrm.idea.MaterialThemeUI, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\JetBrainsClient213.5744.223\plugins\Material Theme UI, version=6.10.1, package=null, isBundled=false), packagePrefix=null, instanceId=4, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 37 more

**Comment by mallowigi** [comment]
Wrong plugin
